"""ASTOLE input schemas for Layer 1 triage.

This module defines the canonical input contract shared between Engineer 1 and
Engineer 2. Canonical field names follow the Spanish v1.1 contract from
`docs/specs/CONTRACT.md`:

- `gnn_metadata.label_multiclase`
- `gnn_metadata.binary_attack`

For backward compatibility, legacy aliases are still accepted at validation
time (`label_multiclass`, `label_binary`) so existing producers do not break.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional

from pydantic import AliasChoices, BaseModel, ConfigDict, Field, field_validator, model_validator


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class AttackCategory(str, Enum):
    """The 9 attack categories from dataset NF-UNSW-NB15-v3 + Benign."""

    BENIGN = "Benign"
    DOS = "DoS"
    FUZZERS = "Fuzzers"
    EXPLOITS = "Exploits"
    BACKDOOR = "Backdoor"
    RECONNAISSANCE = "Reconnaissance"
    ANALYSIS = "Analysis"
    GENERIC = "Generic"
    SHELLCODE = "Shellcode"
    WORMS = "Worms"


# ---------------------------------------------------------------------------
# Sub-models
# ---------------------------------------------------------------------------

class GNNMetadata(BaseModel):
    """Classification metadata generated by the GNN detector."""

    model_config = ConfigDict(populate_by_name=True)

    binary_attack: int = Field(
        ...,
        validation_alias=AliasChoices("binary_attack", "label_binary"),
        serialization_alias="binary_attack",
        description="Binary attack flag (0=Benign, 1=Attack).",
    )
    label_multiclase: AttackCategory = Field(
        ...,
        validation_alias=AliasChoices("label_multiclase", "label_multiclass"),
        serialization_alias="label_multiclase",
        description="NF-UNSW-NB15-v3 multiclass category.",
    )
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="GNN model confidence")
    model_version: str = Field(default="gnn-v3.1", description="Model version that generated the prediction")

    @field_validator("binary_attack", mode="before")
    @classmethod
    def normalize_binary_attack(cls, v: Any) -> int:
        """Accept int, bool and legacy strings ('Attack'/'Benign')."""
        if isinstance(v, bool):
            return int(v)
        if isinstance(v, int):
            if v not in (0, 1):
                raise ValueError("binary_attack must be 0 or 1")
            return v
        if isinstance(v, str):
            cleaned = v.strip().lower()
            if cleaned in {"attack", "1", "true"}:
                return 1
            if cleaned in {"benign", "0", "false"}:
                return 0
        raise ValueError("binary_attack must be 0 or 1")

    @property
    def label_multiclass(self) -> AttackCategory:
        """Legacy alias used by existing internal modules."""
        return self.label_multiclase

    @property
    def label_binary(self) -> int:
        """Legacy alias used by existing internal modules."""
        return self.binary_attack


class NetworkData(BaseModel):
    """NetFlow network data for the flow that triggered the alert."""

    src_ip: str = Field(..., description="Source IP")
    dst_ip: str = Field(..., description="Destination IP")
    src_port: int = Field(..., ge=0, le=65535)
    dst_port: int = Field(..., ge=0, le=65535)
    protocol: int = Field(..., description="IP protocol number (6=TCP, 17=UDP, 1=ICMP)")
    l7_proto: Optional[float] = Field(default=None, description="Optional layer-7 protocol code")
    duration_ms: float = Field(default=0.0, ge=0.0, description="Flow duration in ms")
    in_bytes: int = Field(default=0, ge=0, description="Incoming bytes")
    out_bytes: int = Field(default=0, ge=0, description="Outgoing bytes")
    in_pkts: int = Field(default=0, ge=0, description="Incoming packets")
    out_pkts: int = Field(default=0, ge=0, description="Outgoing packets")
    tcp_flags: int = Field(default=0, ge=0, description="Accumulated TCP flags bitmask")

    @property
    def protocol_name(self) -> str:
        return {6: "TCP", 17: "UDP", 1: "ICMP"}.get(self.protocol, f"OTHER({self.protocol})")

    @property
    def tcp_flags_str(self) -> str:
        """Convert numeric bitmask to readable string (e.g. 18 → 'SA')."""
        flag_map = [
            (0x01, "F"),  # FIN
            (0x02, "S"),  # SYN
            (0x04, "R"),  # RST
            (0x08, "P"),  # PSH
            (0x10, "A"),  # ACK
            (0x20, "U"),  # URG
        ]
        return "".join(letter for mask, letter in flag_map if self.tcp_flags & mask)


class TopFeatures(BaseModel):
    """Top features influencing the GNN decision."""

    f_duration: Optional[float] = None
    f_in_pkts: Optional[int] = None
    f_out_pkts: Optional[int] = None
    f_tcp_flags: Optional[str] = None
    f_retransmitted_in_bytes: Optional[int] = None
    f_flow_duration_ms: Optional[float] = None
    extra: Dict[str, Any] = Field(default_factory=dict)


class WindowStats(BaseModel):
    """Statistics for the 60-second window."""

    total_flows: int = Field(default=1, ge=1)
    attack_flows: int = Field(default=1, ge=0)
    attack_ratio: float = Field(default=0.0, ge=0.0, le=1.0)
    unique_src_ips: int = Field(default=1, ge=1)
    unique_dst_ips: int = Field(default=1, ge=1)


# ---------------------------------------------------------------------------
# Main input model
# ---------------------------------------------------------------------------

class InputAlert(BaseModel):
    """Alert JSON sent by Engineer 1 to the multi-agent pipeline."""

    alert_id: str = Field(..., description="Unique alert ID (e.g. AST-2026-001)")
    timestamp: str = Field(..., description="ISO 8601 detection timestamp")
    window_id: str = Field(default="", description="60s window ID for correlation")
    gnn_metadata: GNNMetadata
    network_data: NetworkData
    @model_validator(mode="before")
    @classmethod
    def merge_technical_details_into_network_data(cls, data: Any) -> Any:
        """Accept v1.1 payloads where flow metrics are inside `technical_details`.

        Engineer 1 may send:
        - `network_data`: connection identity (IPs, ports, protocol, l7_proto)
        - `technical_details`: flow metrics (duration_ms, bytes, pkts, tcp_flags)

        Internal processing expects these metrics in `network_data`, so we merge
        them before field-level validation.
        """
        if not isinstance(data, dict):
            return data
        network_data = dict(data.get("network_data", {}) or {})
        technical_details = dict(data.get("technical_details", {}) or {})
        if technical_details:
            for key in ("duration_ms", "in_bytes", "out_bytes", "tcp_flags", "in_pkts", "out_pkts"):
                if key in technical_details and key not in network_data:
                    network_data[key] = technical_details[key]
            data["network_data"] = network_data
        return data

    top_features: TopFeatures = Field(default_factory=TopFeatures)
    window_stats: WindowStats = Field(default_factory=WindowStats)

    @field_validator("timestamp")
    @classmethod
    def validate_timestamp(cls, v: str) -> str:
        try:
            datetime.fromisoformat(v.replace("Z", "+00:00"))
        except ValueError as e:
            raise ValueError(f"timestamp must be valid ISO 8601: {e}")
        return v
